name: agendamento_consultas_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.1

  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4

  # Utilit√°rios
  uuid: ^4.5.0

  # Banco local (para salvar as consultas no device)
  sqflite: ^2.3.3
  path: ^1.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
